spring:
  cloud:
    gateway:
      routes:
       - id : r1
         uri: http://localhost:8081/
         predicates :
          - Path= /api/users/** 
       - id : r2
         uri: http://localhost:8082/
         predicates :
          - Path= /api/categories/**
  application:
    name: gateway-service
  
   
server:
  port: 8888 